package plugin

import (
	"github.com/xmzo/whoice/services/lookup-api/internal/config"
	"github.com/xmzo/whoice/services/lookup-api/internal/parsers"
	"github.com/xmzo/whoice/services/lookup-api/internal/providers/rdap"
	"github.com/xmzo/whoice/services/lookup-api/internal/providers/whois"
	"github.com/xmzo/whoice/services/lookup-api/internal/providers/whoisweb"
)

func RegisterDefaults(registry *Registry, cfg config.Config) {
	registry.RegisterProvider(rdap.New(cfg.DataDir), cfg.RDAPEnabled)
	registry.RegisterProvider(whois.New(cfg.DataDir), cfg.WHOISEnabled)
	registry.RegisterProvider(whoisweb.New(), cfg.WHOISWebEnabled)
	registry.RegisterParser(parsers.RDAPParser{})
	registry.RegisterParser(parsers.UKWHOISParser{})
	registry.RegisterParser(parsers.JPWHOISParser{})
	registry.RegisterParser(parsers.FRWHOISParser{})
	registry.RegisterParser(parsers.CNWHOISParser{})
	registry.RegisterParser(parsers.BRWHOISParser{})
	registry.RegisterParser(parsers.ITWHOISParser{})
	registry.RegisterParser(parsers.EUWHOISParser{})
	registry.RegisterParser(parsers.BEWHOISParser{})
	registry.RegisterParser(parsers.PLWHOISParser{})
	registry.RegisterParser(parsers.CZWHOISParser{})
	registry.RegisterParser(parsers.HUWHOISParser{})
	registry.RegisterParser(parsers.SKWHOISParser{})
	registry.RegisterParser(parsers.ROWHOISParser{})
	registry.RegisterParser(parsers.MXWHOISParser{})
	registry.RegisterParser(parsers.PTWHOISParser{})
	registry.RegisterParser(parsers.QAWHOISParser{})
	registry.RegisterParser(parsers.MDWHOISParser{})
	registry.RegisterParser(parsers.LUWHOISParser{})
	registry.RegisterParser(parsers.LVWHOISParser{})
	registry.RegisterParser(parsers.AMWHOISParser{})
	registry.RegisterParser(parsers.AXWHOISParser{})
	registry.RegisterParser(parsers.BDWHOISParser{})
	registry.RegisterParser(parsers.BNWHOISParser{})
	registry.RegisterParser(parsers.GGWHOISParser{})
	registry.RegisterParser(parsers.ILWHOISParser{})
	registry.RegisterParser(parsers.LTWHOISParser{})
	registry.RegisterParser(parsers.MOWHOISParser{})
	registry.RegisterParser(parsers.RSWHOISParser{})
	registry.RegisterParser(parsers.STWHOISParser{})
	registry.RegisterParser(parsers.TNWHOISParser{})
	registry.RegisterParser(parsers.UZWHOISParser{})
	registry.RegisterParser(parsers.DEWHOISParser{})
	registry.RegisterParser(parsers.NLWHOISParser{})
	registry.RegisterParser(parsers.CAWHOISParser{})
	registry.RegisterParser(parsers.AUWHOISParser{})
	registry.RegisterParser(parsers.SEWHOISParser{})
	registry.RegisterParser(parsers.FIWHOISParser{})
	registry.RegisterParser(parsers.KRWHOISParser{})
	registry.RegisterParser(parsers.ATWHOISParser{})
	registry.RegisterParser(parsers.RUWHOISParser{})
	registry.RegisterParser(parsers.EEWHOISParser{})
	registry.RegisterParser(parsers.BGWHOISParser{})
	registry.RegisterParser(parsers.KGWHOISParser{})
	registry.RegisterParser(parsers.TRWHOISParser{})
	registry.RegisterParser(parsers.HKWHOISParser{})
	registry.RegisterParser(parsers.TWWHOISParser{})
	registry.RegisterParser(parsers.SIWHOISParser{})
	registry.RegisterParser(parsers.UAWHOISParser{})
	registry.RegisterParser(parsers.IDWHOISParser{})
	registry.RegisterParser(parsers.KZWHOISParser{})
	registry.RegisterParser(parsers.WHOISParser{})
	registry.RegisterBuiltIn("enricher", "epp", cfg.EnrichEPP)
	registry.RegisterBuiltIn("enricher", "registrar", cfg.EnrichRegistrar)
	registry.RegisterBuiltIn("enricher", "brand-map", cfg.EnrichBrands)
	registry.RegisterBuiltIn("enricher", "dns", cfg.EnrichDNS)
	registry.RegisterBuiltIn("enricher", "dnsviz", cfg.EnrichDNSViz)
	registry.RegisterBuiltIn("enricher", "pricing", cfg.EnrichPricing)
	registry.RegisterBuiltIn("enricher", "moz", cfg.EnrichMoz)
	registry.RegisterBuiltIn("enricher", "ai-registration", cfg.AIEnabled)
	registry.RegisterBuiltIn("auth", cfg.AuthMode, cfg.AuthMode != "none")
	registry.RegisterBuiltIn("rate-limit", "builtin", cfg.RateLimitEnabled)
	registry.RegisterBuiltIn("reporter", "prometheus-metrics", cfg.MetricsEnabled)
}
